using OneClickYatra.Api.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OneClickYatra.Api.Services;

public sealed class InvoicePdfService : IInvoicePdfService
{
    private readonly IAgencyBrandingProvider _brandingProvider;

    public InvoicePdfService(IAgencyBrandingProvider __brandingProvider)
    {
        _brandingProvider = __brandingProvider;
    }

    public async Task<byte[]> GenerateAsync(InvoiceModel __invoice, CancellationToken __cancellationToken)
    {
        var profile = await _brandingProvider.GetProfileAsync(__cancellationToken);
        var logoBytes = await _brandingProvider.TryFetchLogoBytesAsync(profile.LogoUrl, __cancellationToken);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(style => style.FontSize(10));

                page.Header().Row(row =>
                {
                    if (logoBytes is not null)
                    {
                        row.ConstantItem(50).Height(50).Image(logoBytes).FitArea();
                        row.ConstantItem(12);
                    }
                    row.RelativeItem().Column(column =>
                    {
                        column.Item().Text(profile.Name).FontSize(20).Bold();
                        column.Item().Text($"Invoice {__invoice.InvoiceNumber}").FontSize(13).FontColor(Colors.Grey.Darken1);
                    });
                });

                page.Content().PaddingTop(15).Column(column =>
                {
                    column.Spacing(8);
                    column.Item().Text($"Billed to: {__invoice.CustomerName}");
                    column.Item().Text($"Booking: {__invoice.BookingNumber}");
                    column.Item().Text($"Issued: {__invoice.IssuedAt:dd MMM yyyy}");

                    column.Item().PaddingTop(16).Row(row =>
                    {
                        row.RelativeItem().Text("Total Amount").Bold();
                        row.ConstantItem(140).AlignRight().Text($"{profile.Currency} {__invoice.Amount:N2}").Bold();
                    });
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span($"Generated by {profile.Name} on ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span(DateTime.UtcNow.ToString("dd MMM yyyy HH:mm") + " UTC").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }
}
