using OneClickYatra.Api.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OneClickYatra.Api.Services;

public sealed class QuotationPdfService : IQuotationPdfService
{
    public byte[] Generate(QuotationModel __quotation, IReadOnlyList<QuotationOptionModel> __options, IReadOnlyDictionary<Guid, List<QuotationItemModel>> __itemsByOptionId)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(style => style.FontSize(10));

                page.Header().Column(column =>
                {
                    column.Item().Text("One Click Yatra").FontSize(20).Bold();
                    column.Item().Text($"Quotation {__quotation.QuotationNumber}").FontSize(13).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingTop(15).Column(column =>
                {
                    column.Spacing(8);
                    column.Item().Text($"Prepared for: {__quotation.LeadCustomerName}");
                    if (__quotation.ValidUntil.HasValue)
                    {
                        column.Item().Text($"Valid until: {__quotation.ValidUntil.Value:dd MMM yyyy}");
                    }
                    if (!string.IsNullOrWhiteSpace(__quotation.Notes))
                    {
                        column.Item().Text(__quotation.Notes).FontColor(Colors.Grey.Darken2);
                    }

                    foreach (var option in __options)
                    {
                        column.Item().PaddingTop(12).BorderTop(1).BorderColor(Colors.Grey.Lighten2).PaddingTop(8).Column(optionColumn =>
                        {
                            optionColumn.Spacing(4);
                            optionColumn.Item().Row(row =>
                            {
                                row.RelativeItem().Text(option.OptionName).FontSize(13).Bold();
                                if (option.IsRecommended)
                                {
                                    row.ConstantItem(90).AlignRight().Text("Recommended").FontColor(Colors.Green.Darken1).Bold();
                                }
                            });

                            var summaryParts = new List<string>();
                            if (!string.IsNullOrWhiteSpace(option.DestinationName)) summaryParts.Add(option.DestinationName);
                            if (option.DurationDays.HasValue || option.DurationNights.HasValue) summaryParts.Add($"{option.DurationDays ?? 0}D/{option.DurationNights ?? 0}N");
                            if (!string.IsNullOrWhiteSpace(option.HotelCategory)) summaryParts.Add(option.HotelCategory);
                            if (summaryParts.Count > 0)
                            {
                                optionColumn.Item().Text(string.Join(" · ", summaryParts)).FontColor(Colors.Grey.Darken1);
                            }

                            var items = __itemsByOptionId.TryGetValue(option.Id, out var found) ? found : [];
                            if (items.Count > 0)
                            {
                                optionColumn.Item().PaddingTop(4).Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.RelativeColumn(3);
                                        columns.RelativeColumn(1);
                                    });

                                    foreach (var item in items)
                                    {
                                        table.Cell().Text(item.Description);
                                        table.Cell().AlignRight().Text($"Rs. {item.Amount:N0}");
                                    }
                                });
                            }

                            optionColumn.Item().PaddingTop(4).Row(row =>
                            {
                                row.RelativeItem().Text($"Price per person ({option.NumberOfPeople} pax)");
                                row.ConstantItem(120).AlignRight().Text($"Rs. {option.PricePerPerson:N0}");
                            });
                            optionColumn.Item().Row(row =>
                            {
                                row.RelativeItem().Text("Total").Bold();
                                row.ConstantItem(120).AlignRight().Text($"Rs. {option.TotalPrice:N0}").Bold();
                            });
                        });
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by One Click Yatra on ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span(DateTime.UtcNow.ToString("dd MMM yyyy HH:mm") + " UTC").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }
}
