using OneClickYatra.Api.Models.Responses;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OneClickYatra.Api.Services;

public sealed class VoucherPdfService : IVoucherPdfService
{
    private readonly IAgencyBrandingProvider _brandingProvider;

    public VoucherPdfService(IAgencyBrandingProvider __brandingProvider)
    {
        _brandingProvider = __brandingProvider;
    }

    public async Task<byte[]> GenerateAsync(BookingDetailResponse __detail, CancellationToken __cancellationToken)
    {
        var booking = __detail.Booking;
        var profile = await _brandingProvider.GetProfileAsync(__cancellationToken);
        var logoBytes = await _brandingProvider.TryFetchLogoBytesAsync(profile.LogoUrl, __cancellationToken);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(style => style.FontSize(10));

                page.Header().Row(row =>
                {
                    if (logoBytes is not null)
                    {
                        row.ConstantItem(50).Height(50).Image(logoBytes).FitArea();
                        row.ConstantItem(12);
                    }
                    row.RelativeItem().Column(column =>
                    {
                        column.Item().Text(profile.Name).FontSize(20).Bold();
                        column.Item().Text($"Travel Voucher — Booking {booking.BookingNumber}").FontSize(13).FontColor(Colors.Grey.Darken1);
                    });
                });

                page.Content().PaddingTop(15).Column(column =>
                {
                    column.Spacing(8);
                    column.Item().Text($"Guest: {booking.CustomerName}");
                    column.Item().Text($"Destination: {booking.DestinationName ?? "—"}");
                    column.Item().Text($"Package: {booking.PackageTitle ?? "—"}");
                    column.Item().Text($"Travel Date: {(booking.TravelDate.HasValue ? booking.TravelDate.Value.ToString("dd MMM yyyy") : "—")}");
                    column.Item().Text($"Return Date: {(booking.ReturnDate.HasValue ? booking.ReturnDate.Value.ToString("dd MMM yyyy") : "—")}");
                    column.Item().Text($"Travellers: {booking.NumberOfAdults} adult(s), {booking.NumberOfChildren} child(ren)");
                    column.Item().Text($"Status: {booking.Status}");

                    if (__detail.Passengers.Count > 0)
                    {
                        column.Item().PaddingTop(12).Text("Passengers").Bold();
                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(2);
                            });

                            foreach (var header in new[] { "Name", "Age", "Gender", "ID Proof" })
                            {
                                table.Cell().Background(Colors.Grey.Lighten3).Padding(3).Text(header).Bold();
                            }

                            foreach (var passenger in __detail.Passengers)
                            {
                                table.Cell().Padding(3).Text(passenger.FullName + (passenger.IsLeadPassenger ? " (Lead)" : string.Empty));
                                table.Cell().Padding(3).Text(passenger.Age?.ToString() ?? "—");
                                table.Cell().Padding(3).Text(passenger.Gender ?? "—");
                                table.Cell().Padding(3).Text(passenger.IdProofType is null ? "—" : $"{passenger.IdProofType}: {passenger.IdProofNumber}");
                            }
                        });
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span($"Generated by {profile.Name} on ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span(DateTime.UtcNow.ToString("dd MMM yyyy HH:mm") + " UTC").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }
}
